version: "3.7"
services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ScalableProgramming
      MONGO_INITDB_ROOT_PASSWORD: ScalableProgrammingPassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ScalableProgramming
      ME_CONFIG_MONGODB_ADMINPASSWORD: ScalableProgrammingPassword
      ME_CONFIG_MONGODB_URL: mongodb://ScalableProgramming:ScalableProgrammingPassword@mongo:27017/
    depends_on:
        - mongo


volumes:
  mongodb_data_container: